version: "3"
services:
  bot:
    image: zead0n/zeabot
    container_name: zeabot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data